allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
parameters:
  if()
  {{- range $key, $value := .Values.storageClass.parameters }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
provisioner: {{ .Values.storageClass.provisioner }}
reclaimPolicy: Delete
volumeBindingMode: Immediate
