apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignite-client-deployment
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ignite-client
  template:
    metadata:
      labels:
        app: ignite-client-deployment
        date: 7thApril2022
    spec:
      serviceAccountName: ignite-client-sa
      containers:
        - name: ignite-client
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /manage/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 60