apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ignite-app
  namespace: ignite
spec:
  hosts:
    - "{{ .Values.istio.hosts }}"
  gateways:
    - default/backend-gateway
  http:
    - name: ignite
      match:
        - uri:
            prefix: /ignite
      rewrite:
        uri: /ignite/$2
      route:
        - destination:
            host: ignite-service
            port:
              number: 8080