apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: gridgain-dest-rule
  namespace: gridgain
spec:
  host: "gridgain.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL